---  
title: "A heirarchical age-structured assessment model for 5 species of British Columbia right-eyed flounders (Pleuronectidae) in three stock areas."
author: 
  - Samuel D. N. Johnson (corresponding)
  - Sean P. Cox
affil:
  - School of Resource and Environmental Management,
    Simon Fraser University,
    8888 University Drive,
    BC, Canada
email:
  - samuelj@sfu.ca
  - spcox@sfu.ca
date: \today
bibliography: /Users/sdnjohnson/Work/Library/library.bib
csl: /Users/sdnjohnson/Work/write/templates/csl/cjfas.csl 
geometry: letterpaper
toc: false
fontsize: 12pt
lineno: true
numbersections: false
appendix: false
abstract: Fisheries stock assessments are typically performed for a single species or stock at a time. Not all stocks have the same available data (e.g. missing age structures), due to low fishing effort or sampling effort, so go un-assessed or get aggregated with other management units, despite heterogeneity in abundance or biological data. Modern hierarchical multi-species and multi-stock assessment models are an alternative option for dealing with data limitations in spatially diverse fisheries. For example, biological information can be shared between stocks within a species, and environmental effects may be experienced similarly by species that inhabit the same stock area. In this paper, we present a multi-species, multi-stock, age and sex structured integrated stock assessment model, able to be fit to abundance, age, and length data for five right-eyed flounder (Pleuronectidae) species in three stock areas on the coast of British Columbia. For two of those species, at least one stock area was missing age composition data, so length compositions were the primary compositional data used to detect recruitment signals in those stocks, and by implication no growth model was estimable for those stocks due to missing length-at-age observations. To share information between stocks, hierarchical shrinkage priors were formulated for catchability, natural mortality, stock-recruit steepness, selectivity-at-length, and von Bertalanffy asymptotic length parameters. We compared the assessment results under multiple model hypotheses and data scenarios, varying prior belief in hierarchical prior hypervariance parameters, assessment model initialisation times, and switching between time-varying and constant observation model parameters. Integrated growth model/first assessments of many stocks/... Results...
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/basic.latex
  bookdown::pdf_document2:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ~/Work/write/templates/tex/basic.latex
  html_document:
    self_contained: true
    df_print: kable
    keep_md: true
  bookdown::html_document2:
    self_contained: true
    df_print: kable
    keep_md: true
  word_document:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
  bookdown::word_document2:
    df_print: kable
    reference_docx: /Users/sdnjohnson/Work/write/templates/docx/basic.docx
---

```{r SetupBody, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(figurepos = 'p') # Places figures on their own pages
knitr::opts_chunk$set(out.width = '100%', dpi=300)

# I usually load my libraries up front to keep things organized
library(rmarkdown)
library(knitr)
library(kableExtra)
library(dplyr)
library(stringr)
library(bookdown)

```


# Introduction

Fisheries stock assessment is concerned with determining the status of exploited fish stocks under uncertainty [@hilborn1992quantitative]. Stock assessment models are fit to multiple sources of data, including abundance or biomass indices, age compositions, length composition data, and age-at-length data.

Fisheries management typically focuses on a single stock of a single species at a time. This narrow focus often implictly assumes that fish are uniformly distributed across the management area, ignoring any spatial structure, and ignores interactions between species, except implicitly through recruitment or mortality [@albertsen2017connecting; @siple2017contributions].

Data limitations - modern fisheries management is based on fitting age structured models, age data is often missing as it is costly to collect. Age data provides signals to help estimate selectivity, mortality, and recruitment. Length compositions are commonly used as an alternative when age data is missing, but often lack contrast around the asymptotic length of a species, especially for fast growing species that are rarely encountered by surveys or commercial effort.

Hierarchical multi-stock and multi-species stock assessment models offer an alternative to increasing costly age readings for low-abundance or importance stocks.
    - Sharing information [@johnson2018evaluating; punt2011among; @jiao2011poor]

In this paper, we apply a hierarchical multi-stock age-structured assessment model to a complex of 5 Pleuronectiforme flatfishes off the coast of British Columbia. 
    - DERPA
    - Different historic levels of exploitation/conservation concern
    - Multiple spatial scales?
    - Technical interactions - caught together (though not all)
    - estimating correlations in fishing/total mortality and recruitment (emmig/immig and technical interactions) - Read Siple paper again
    - Integrated growth model - look at integrated assessment model literature
    - shared priors on catchability [@johnson2018evaluating], steepness [@myers1999maximum], mortality [@albertsen2017connecting], selectivity, growth model pars [@piner2016evaluation]


# Methods

## Study system

British Columbia's groundfish trawl fishery is one of 7 fisheries that operate on the BC coast. The entire groundfish fishery is managed using one integrated individual transferrable quota system, allowing transfers of quota allocations between licenses in different fleets. 

DERPA complex:
    - Dover sole, english sole, southern rock sole, petrale sole, and arrowtooth flounder.
    - All flatfish that are subject to managed/directed removals except Halibut, which are managed by the IPHC
    - History of DERPA??
    - DERPA is encountered mainly by the groundfish trawl fishery, with negligible removals from the other sectors/gear types
    - List assessments?

Not all stocks are surveyed equally: different stocks have large samples age structures, others have no samples at all. 
    - Length composition data supplement the age observations [@rudd2017accounting]
    - Integrated hierarchical growth model shares growth data between stocks and species [@cadigan2017hierarchical], allows for unbiased estimation of age/length observations - e.g. Random-at-length obs, conditioned on fleet selectivity and modeled age structure [@piner2016evaluation]
    - Can use hierarchical RAL growth model to extend growth hypotheses to stocks with missing data in a data-driven way (e.g. estimating a growth model for the stocks with missing age data), allowing for an age structured model for stocks with missing age data


## Data

- Relative biomass from fishery independent surveys (1984 - 2017) (Source)
- Fishery dependent CPUE (1956 - 2017) (Source)
- Age and length composition data (surveys and commercial fleet)
    * Explain stocks with missing data?
- Conditional age-at-length data by fleet group


## Stock assessment model

The stock assessment model has an age structured process model that explicitly includes uncertainty in the length-at-age distribution. Length-at-age distributions for each stock are estimated by fitting a hierarchical growth model to conditional age-at-length data for each stock and species. 

**Equations are given in Table XX/Supplemental material**

For stocks without age observations, length comps for each stock are used in the observation model. To avoid using the same data twice, we only use length compositions from individual fish where age was not observed. For fish where age was observed, accompanying length observations are available, and this data was used to fit the integrated random-at-length Von Bertalanffy growth model

Hierarchical priors:
- integrated Schnute formulation of vonB growth model [@schnute1981versatile; @francis2016growth]
    - vonB K parameter between stocks
    - K, L2 and sigmaL within species
    - Random-at-length, using modeled age structure and selectivity inside the model
- Steepness between stocks and species (multilevel)
- Catchability for fleet groups
- M between stocks and species (multilevel)
- Correlations in recruitment deviations?
- Selectivity-at-length parameters - this will probably play well with the compositional data issues below

Multifleet model: one fleet for each survey leg in Synoptic (WCHG, HS, QCS, and WCVI), one for the HS Assemblage survey, and two commercial trawl fleets (historic and modern). These fleets naturally fall into three groups (Commercial Trawl, Assemblage survey, and Syboptic surveys), so a hierarchical prior structure was defined based on those groups for observation model parmeters, e.g.



Compositional data: This might be the crux of this paper/analysis, i.e. what to do about compositional data. 

+ What to do about selectivity - time-varying to follow bad fitting compositions?
+ Papers:
    * @francis2017revisiting, 
    * @francis2016growth; 
    * @francis2014replacing; 
    * @stewart2017implications; 
    * @thorson2014standardizing; 
    * @thorson2018spatiotemporal; 
    * @thorson2014mixed;




## Model Hypotheses / Data scenarios

Here I need to include the data scenarios and model hypotheses I'm going to test. If I'm going to publish an assessment, then it needs to be a *thorough* assessment. So, what are our options:

1. Different hierarchical model structures
    a. Coastwide vs stock specific growth
    b. Different correlation matrix structures for Recruitment process errors - post-hoc analysis of correlations?
    c. Smaller or larger hyperprior on hypervariance on multi-level priors
3. Multi-species vs single species/multi-stock
4. Data scenarios:
    a. Starting in 1956, 1984, 1996, 2003
    b. Age only, length only [No growth model], age/length?
5. Discarding? Contact Bruce Turris or Greg Workman about a grading length


## Optimisation and inference

- Integrated over random effects
- Bayesian or RE?

## Model selection criteria

AIC is standard, but need to calculate eff. number of parameters, and what about for choosing between two different data scenarios, e.g. coastwide vs multi-stock, different initial times? Cross validation?? Comparison of reference points



## Reference points and fishery performance

We calculated biological reference points based on equilibrium maximum sustainable yield (MSY) 
(see supplemental for equilibria definitions). While MSY is a controversial management quantity, 
it is important to note that we do not recommend MSY as a target value, 
but as an upper bound on the absolute allowable catch of fish from a given a stock 
[@larkin1977epitaph]. We instead follow the recommendation that the associated fishing mortality 
rate $F_{MSY}$, or harvest rate $U_{MSY}$, be used as an upper limit on fishing mortality,
and that the associated spawning stock biomass $B_{MSY}$ be used as a target biomass 
[@smith2001gospel].

**CHECK THAT FMSY IS APPROPRIATE, smith and punt suggest we used F0.1**

To determine historical fishery performance, we calculated the proportion 
of stocks that were underexploited, fished 'just right', or overexploited, 
in each year [@hilborn2018measuring]. We defined under-exploited as either the 
fishing mortality rate $F$ being *less than* the reference rate $F_{MSY}$, or biomass being above
$1.2 \cdot B_{MSY}$, while overexploited was defined as $F > F_{MSY}$ or spawning
biomass being below $0.8 \cdot B_{MSY}$. These bounds are based on the management
targets used in **GET FROM HILBORN PAPER and CHECK SFF**.


# Results

We found that
  - describe stock status of each species, indicate those that are in poor states/good states compared to their reference points.
  - Compare dover sole to @johnson2018evaluating, other species to other previous assessments

Different data scenarios showed that:
  - Adding length comps (reduced/increased) uncertainty for stocks with no age comps




 
# Discussion

In this paper we fit a hierarchical age-structured stock assessment to 5 species of flatfish, each with 3 stocks.

Challenges:
  - Fitting to length comps (you better get the biology right (ref))
  - overwhelming the likelihood with compositional data
  - integrating growth vs leaving it out

Limitations:
  - No movement
  - No technical/trophic interactions (bycatch ratios??)
  - 

Conclusion:
  - Despite limitations, these hierarchical stock assessment models are a viable method of extending assessments to management units where data are limited or non-existent
  - 

Future work: 
    - using this as an operating model to test multi-speces management objectives - could use simpler AM, such as multispecies coastwide, or a DD or SP model.
    - Adding movement hypotheses
    - Adding bycatch - especially for testing above multi-species management objectives, want to have choke effects as an emergent property
    - Adding high-grading


# References













